#!/bin/bash -e


# navigate to seisflows/tests
cd $(dirname ${BASH_SOURCE[0]})


WD="$PWD/setup/test_system"


echo "TESTING SERIAL..."
rm -rf $WD/output* $WD/scratch
sfrun --workdir=$WD --parameter_file=$WD/parameters_serial --path_file=$WD/paths
rm -rf $WD/output* $WD/scratch


echo "TESTING multicore..."
rm -rf $WD/output* $WD/scratch
sfrun --workdir=$WD --parameter_file=$WD/parameters_multicore --path_file=$WD/paths
rm -rf $WD/output* $WD/scratch


#echo "TESTING pbs_torque_small..."
#sfrun --workdir=$WD --parameter_file=$WD/parameters_pbs_torque_sm --path_file=$WD/paths
#rm -rf $WD/output* $WD/scratch
